### ISSUE TITLE
Great Tutorials - new syntax for v 1.0.9

### ISSUE THREAD

**Issue by BLOC8app** [hx57/ICON-SDK-Tutorial#1]
Can you update the syntax for v 1.0.9,  new:

`icon_service = IconService(HTTPProvider("https://bicon.net.solidwallet.io/",  3))`

rather than:

`icon_service = IconService(HTTPProvider("https://bicon.net.solidwallet.io/api/v3"))`

Old syntax still works but it warns that it's depreciated.

**Comment by Spl3en** [comment]
Thanks for the suggestion ! Fixed
